const auto_start = document.querySelector("#auto-start")
const min = document.querySelector("#min")
const cycles = document.querySelector("#pomodoros")
const min_break = document.querySelector("#min-break")
const save = document.querySelector("#save")
const min_longbreak = document.querySelector("#min-longbreak")
